export const titles: {
    [key: string]: string;
} = {
    "archive-create": "Criar arquivo",
    "egress-list": "Lista de Egressos",
    "egress-list-disableds": "Lista de Egressos Excluídos",
    "egress-create": "Cadastrar Egresso",
    "archive-list": "Lista de Arquivos",
    "users-list": "Lista de Usuários",
    "users-create": "Cadastrar Usuário",
    "hierarchy-create": "Cadastrar Hierarquia",
    "hierarchy-list": "Lista de Hierarquia",
    "egress-dettach": "Desvincular Egresso",
    "egress-attach": "Vincular Egresso",
    "first-access": "Primeiro Acesso",
    "forget-password": "Esqueci minha senha",
    "egress-delete": "Deletar Egresso",
    "hierarchy-update": "Atualizar Hierarquia",
    "hierarchy-delete": "Deletar Hierarquia",
    "hierarchy-add-user": "Adicionar Usuário",
    "remove-user": "Remover Usuário",
    "users-list-disableds": "Lista de Usuários Desativados",
    "users-update": "Atualizar Usuário",
    "hierachy-users-delete": "Remover Usuário",
    "egress-edit": "Atualizar Egresso",
    "archive-delete": "Deletar Arquivo",
    "hierarchy-remove-user": "Remover Usuário",
    "users-delete": "Deletar Usuário",
    "school-list": "Lista de Escolas",
    "school-create": "Cadastrar Escola",
    "school-update": "Atualizar Escola",
    "school-delete": "Deletar Escola",
    "should-reset-password": "Redefinir Senha",
    "archive-attach-egress": "Vincular Arquivo ao Egresso",
    "archive-detach-egress": "Desvincular Arquivo do Egresso",
    "excel-import": "Anexar arquivo de egresso",
    "excel-export": "Exportar arquivo de egresso",
}
