name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}

    steps:
    - uses: actions/checkout@v4
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      id: cache-yarn
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: $ {{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}\-${{ hashFiles('**/yarn.lock') }}
        restore-keys:
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: yarn list

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: |
        yarn install
        yarn build